import client, { withIdempotencyKey } from './client'

/**
 * Fetch all payouts for a merchant.
 * GET /api/v1/payouts/?merchant_id=...
 *
 * @returns {Array} list of payout objects
 */
export async function getPayouts(merchantId) {
  try {
    const response = await client.get('/api/v1/payouts/', {
      params: { merchant_id: merchantId },
    })
    return response.data
  } catch (error) {
    console.error('[getPayouts] failed:', error.response?.data ?? error.message)
    throw error
  }
}

/**
 * Create a new payout request.
 * POST /api/v1/payouts/
 * Requires an Idempotency-Key header to prevent duplicate submissions.
 *
 * @param {{ merchant_id: string, amount_paise: number, bank_account_id: string }} data
 * @param {string} idempotencyKey - UUID string, generated by the caller
 * @returns {{ payout_id: string, status: string, amount_paise: number }}
 */
export async function createPayout(data, idempotencyKey) {
  try {
    const response = await client.post(
      '/api/v1/payouts/',
      data,
      withIdempotencyKey(idempotencyKey),
    )
    return response.data
  } catch (error) {
    console.error('[createPayout] failed:', error.response?.data ?? error.message)
    throw error
  }
}
