# Generated by Django 4.2.30 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
